

386_OBJECTS=\
 $(OBJ_PATH)\$O\purecall.obj \
 $(OBJ_PATH)\$O\device.obj \
 $(OBJ_PATH)\$O\filter.obj \
 $(OBJ_PATH)\$O\image.obj \
 $(OBJ_PATH)\$O\capture.obj \
 $(OBJ_PATH)\$O\hwsim.obj \


_RES_FILE=$(OBJ_PATH)\$O\avshws.res



# lowercased
BASEDIR=d:\soft\programming\wdk\7600.16385.1
OBJECT_ROOT=d:\soft\programming\wdk\7600.16385.1
MAKEDIR_LOWERCASE=d:\projects\drivers\test\avshws
OBJ_PATH=d:\projects\drivers\test\avshws
CONCURRENT_MIDL=0
CONCURRENT_MANIFEST_BUILD=0
